# AfterCloud Uptime config
# If you need help, join our discord server here: https://discord.gg/zv6maQRah3

# Bot Info's
token: 'ODg1ODQ5MTU0NTIwMjI3ODUx.YTtBUA.sgBkpClBDGp16XCMegevKwTYRxU'
botstatus:
  enable: 
  text: 'HOSTING'
  type: ''


channel: '' #
refreshtime: 10

panel:
  url: 'https://console.mariclecraft.xyz'
  adminkey: '0OJzr4mOe3UdGq2xLa2JlbKPneoSJwT1TkC6uGPvcaXKas0g'
embed: 
  title: ''
  color: '00fdff'
  description: 
    enable: false
    text: 'EMBED DESCRIPTION'
  footer: 
    enable:
    text: 'Uptime System'
  timestamp: 
status:
  online: ':green_circle: Up'
  offline: ':red_circle: Down'
  check: ':orange_circle: Checking'

# Node Resource
resource:
  enable: true
  servers: true
  allocations: true
  location: true
  unit: 'percent''

# Developers feature
debug: false # Enable and Disable debug log to console
debugaxios: false #Enable and Disable axios error logs
